//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App2Aapp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App2Aapp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is turned off. To see the current Bluetooth settings tap &apos;ok&apos;..
        /// </summary>
        public static string Err_BluetoothOff {
            get {
                return ResourceManager.GetString("Err_BluetoothOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Off.
        /// </summary>
        public static string Err_BluetoothOffCaption {
            get {
                return ResourceManager.GetString("Err_BluetoothOffCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run this app, you must have ID_CAP_PROXIMITY enabled in WMAppManifest.xaml.
        /// </summary>
        public static string Err_MissingCaps {
            get {
                return ResourceManager.GetString("Err_MissingCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a chat name to join..
        /// </summary>
        public static string Err_NoChatName {
            get {
                return ResourceManager.GetString("Err_NoChatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name is empty.
        /// </summary>
        public static string Err_NoChatNameCaption {
            get {
                return ResourceManager.GetString("Err_NoChatNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect.
        /// </summary>
        public static string Err_NoConnectTitle {
            get {
                return ResourceManager.GetString("Err_NoConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a message to send..
        /// </summary>
        public static string Err_NoMessageToSend {
            get {
                return ResourceManager.GetString("Err_NoMessageToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a peer from the list..
        /// </summary>
        public static string Err_NoPeer {
            get {
                return ResourceManager.GetString("Err_NoPeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to a Peer..
        /// </summary>
        public static string Err_NoPeerConnected {
            get {
                return ResourceManager.GetString("Err_NoPeerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send.
        /// </summary>
        public static string Err_NoSendTitle {
            get {
                return ResourceManager.GetString("Err_NoSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently not advertising yourself, i.e., a call to PeerFinder.Start() must proceed FindAllPeersAsync().
        /// </summary>
        public static string Err_NotAdvertising {
            get {
                return ResourceManager.GetString("Err_NotAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to chat with {0}?.
        /// </summary>
        public static string Msg_ChatPrompt {
            get {
                return ResourceManager.GetString("Msg_ChatPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomming Chat.
        /// </summary>
        public static string Msg_ChatPromptTitle {
            get {
                return ResourceManager.GetString("Msg_ChatPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot run this sample in the emulator because Bluetooth is not enabled. To see the sample working, run it on a Windows Phone 8 device..
        /// </summary>
        public static string Msg_EmulatorMode {
            get {
                return ResourceManager.GetString("Msg_EmulatorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
